# Generated by Django 3.2 on 2021-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postRG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='reciever_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='sender_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='value',
            field=models.IntegerField(),
        ),
    ]
