# Generated by Django 3.2 on 2021-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postRG', '0002_auto_20210424_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='reciever_address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='sender_address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
