# Generated by Django 3.2 on 2021-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postRG', '0003_auto_20210424_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttoken',
            name='reciever_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posttoken',
            name='sender_balances',
            field=models.IntegerField(default=0),
        ),
    ]
