# Generated by Django 3.2 on 2021-04-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postRG', '0004_auto_20210424_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttoken',
            name='private_key',
            field=models.CharField(default='', max_length=150),
        ),
    ]
